### ISSUE TITLE
GridLY: Warning about missing Voice for lyrics

### ISSUE THREAD

**Issue by uliska** [openlilylib/snippets#63]
When compiling the example file and specifying 3 or 4 (or `#'(3 . 4)` GridLY (or rather LilyPond) will complain about not finding a Voice for the Lyrics. Output is OK, however.

Is it possible to somehow detect and suppress this condition?

**Comment by Cecca** [comment]
LilyPond issues that warning because the bass part for segments 3 and 4 has no notes, so LilyPond can't find notes to attach the lyrics to (even if there are no lyrics). As soon as a note is entered in one of those cells the warning disappears.

So I think that this warning is quite appropriate. Since the output is OK and the warning is useful, I don't think we should suppress it.

**Comment by Cecca** [comment]
If for you is OK, @uliska , I'm going to close this as a `wontfix`, since the warning actually makes sense.

**Comment by uliska** [comment]
Would it be possible to suppress the warning when no lyrics are present either?
I do have the situation that there are voices defined, and a score using `\getGridMusic` and `\getGridLyrics`, and when both are empty there are these warnings. And in this case they don't make that much sense.

**Comment by Cecca** [comment]
OK, I'll have a look at this. Maybe `gridGetLyrics` should return `#{ #}` if there is no music defined in the same cell.

**Comment by uliska** [comment]
Am 23.03.2015 um 09:37 schrieb Matteo Ceccarello:

> OK, I'll have a look at this. Maybe |gridGetLyrics| should return |#{ 
> #}| if there is no music defined in the same cell.

Maybe, but I'm not sure if that solves the problem. AFAICS it should 
rather be ensured that \gridGetMusic produces a Voice even if there's no 
content.

**Comment by Cecca** [comment]
The fact is that gridGetMusic does not produce directly a Voice, it just returns the music. So maybe this is something that should be addressed in the template file.

**Comment by uliska** [comment]
Hm, you're right.
However, it doesn't solve the problem. The staves are created using

``` lilypond
vocalStaff =
#(define-music-function (parser location name props)
   (string? ly:music?)
   #{
     \new Staff = #name <<
       \new Voice = #name {
         #props
         \gridGetMusic #name
       }
       \new Lyrics \lyricsto #name {
         \gridGetLyrics #name
       }
     >>
   #})
```

so an explicit voice _is_ created, but still when there's no content the warnings appear.
I'll investigate if that's related to my project or GridLY, or if it's rather a LilyPond thing (and if so if it is a bug or just normal behaviour).
